name: Build doc

on:
  push:
    paths-ignore:
      - ".github/**"
  pull_request:
    paths-ignore:
      - ".github/**"


jobs:
  build:
    name: Build doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python -m pip install --user -r ./requirements.txt
      - name: Build docs
        run: make html
